### ISSUE TITLE
It seems impossible to choose a server which is not on the list

### ISSUE THREAD

**Issue by chagai95** [mastodon/mastodon-android#102]

**Comment by sk22** [comment]
Agreed - it should be more clear that the text field isn't only a search box, but can also take links to other instances.

**Comment by grishka** [comment]
It literally says "or URL" on there...

**Comment by sk22** [comment]
Yes, but it also has a search icon, is placed on top of a list, and looks like a search box - because it primarily is one. The "or enter URL" can easily be overlooked. (And also, I don't expect everyone to know exactly what a URL is - also, strictly speaking, "todon.eu" e.g. isn't one (without the https://), so maybe "or enter server address" would be better.)
I don't know how exactly to improve this, but it's not ideal the way it is imo.

**Comment by chagai95** [comment]
Actually I meant I put a url/link/server address and it didn't work...

@chagai95@campaign.openworlds.info

**Comment by chagai95** [comment]
So I put https://campaign.openworlds.info and the button on the bottom to contribute was still grey..

**Comment by sk22** [comment]
> So I put https://campaign.openworlds.info and the button on the bottom to contribute was still grey..

oh huh, so it's really only the domain name (campaign.openworlds.info) that's understood by the app…

**Comment by grishka** [comment]
The next version will accept URLs as well.

**Comment by grishka** [comment]
That version was since released.
