### ISSUE TITLE
Feature request: Back button returns to Home timeline

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#118]
Similar to Twitter or Husky, I think it would be useful to have the back button first return to the Home timeline before exiting the app.

**Comment by grishka** [comment]
No, I absolutely oppose that. The back button should never, ever, under any circumstances, interact with tab bars. Back button is for going back in _hierarchical_ navigation. It is hierarchical when, for example, you open someone's profile from the home timeline. It is not hierarchical when you switch tabs — it's lateral, you still remain on the same hierarchy level.

All those apps that make the back button switch tabs are bad, and they are probably made or managed by clueless iPhone users.

**Comment by sk22** [comment]
I totally get your point and I think you're right about it, at least in theory - because in praxis, people (at least myself) are used to pressing back to return to the Home timeline as it's how many other apps implement it (Twitter, Instagram, hell, even Tinder does it like this). I've found myself accidentally closing the app more than once because of this. But anyway:

> All those apps that make the back button switch tabs are bad, and they are probably made or managed by clueless iPhone users.

Seriously? You know that you're not only insulting devs of big corporations, but also independent devs of apps like Tusky (and also iPhone users, for some reason)?

**Comment by Benji7103** [comment]
As someone who uses mastodon on iOS and android: the experience of not accidentally closing the app is nice

**Comment by grishka** [comment]
> people (at least myself) are just used to pressing back to return to the Home timeline as it's how many other apps implement it (Twitter, Instagram, hell, even Tinder does it like this). I've found myself accidentally closing the app more than once because of this.

On the other hand, I myself find it annoying that those apps *don't* close when I press the back button. Especially Instagram. It's the worst offender. It even goes out of its way to remember the history of tabs for some reason. If you scroll the feed, then go to notifications, then go to search, successive presses of the back button will:
- Open the notifications tab
- Open the home timeline tab
- Scroll the timeline up (!!)
- Scroll the stories to the beginning if they're not there
- Finally, close the activity

> "Am I out of touch? No, it's those clueless iPhone users who are wrong."

Sorry if it comes off rude. I just spent way too much time during my previous jobs arguing with someone who uses an iPhone full-time about how their ideas of how things should work in Android are wrong. In big corporations especially, management, the people who actually make decisions, often use iPhones — this is how we get behavior like Instagram has. And then, because so many big-corp apps do it, smaller devs think it's the norm and copy this behavior. *Some* of Google's own apps even do this, but others don't.

Just an anecdote of how bad it gets at times. My first job was VKontakte, the Russian social media company. I was the first Android developer there. Pavel Durov, founder, was still the CEO at the time. He, of course, used an iPhone. He would sometimes buy the current Samsung flagship, show it to me saying "Grisha, see, I'm using Android", then go back to iPhone in several days. Anyway. For the first release, he not only wanted the app to look like it was ported from iOS, he insisted that there's some kind of on-screen back button in the title bar (it's 2011, ActionBar was not invented yet). I tell him that no, you don't need that, Android phones all have a hardware back button. He still insists that we add one. So I kinda give up, the designer draws a very iOS-like back button, and I add it. In one last attempt, I ask him if I can at least add a setting to hide this thing. He agrees. I add a setting and make it default to "off". We ship the release. People install the app and wonder what's the deal with that setting to enable an on-screen back button. The setting, and the button, got removed eventually. It only took me 3 years to convince Pavel we need to follow the platform UI guidelines (Holo at the time) and redesign our app in accordance with them.
