### ISSUE TITLE
Feature: Follow hashtags

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#233]
Just like in the web UI it should be possible to follow hashtags.

**Comment by tjkirch** [comment]
In the web UI, you can also pin hashtags so they appear in a separate column. That would be a great related addition, at least for people like me, because I don't want my home cluttered with hashtag messages. Hashtag results could be a separate tab.

**Comment by jamfx** [comment]
Is this somehow solved or planned yet? I'm missing this feature very much. Thanks for the work.
Niko

**Comment by grishka** [comment]
It is planned for a future release.

**Comment by jamfx** [comment]
Is there a schedule for this? Since this is open since July?

**Comment by bgta** [comment]
Is there any schedule for this feature? It has been requested for more than 200 days, and I think it is a basic feature in a federated network where hashtags are so important.

**Comment by mattwelke** [comment]
It's a popular feature request, yes, but if I recall, there are very few people who work full time on Mastodon and its related projects, like this app. We need to [fund the developers more](https://www.patreon.com/mastodon) if we want to see more progress on these feature requests.

**Comment by grishka** [comment]
The feature is still planned but we're doing a UI redesign right now to fit better with the current Material guidelines. I'll be back to building new features after the redesign is complete.

**Comment by ahrnbom** [comment]
I imagine that adding this feature is simply adding a simple button in the hashtag search results, and connecting it to an existing API. Would the Mastodon Android app team accept a pull request for such a feature now, before the redesign? I might be able to help here, if I can find the time, because I'd really, really like this feature :)

**Comment by leohumnew** [comment]
Would be great if this could be worked on! Following hashtags is such a basic and essential feature for Mastodon and having to use the website adds a lot of friction. I know there's very limited Dev time but I feel like it should surely be quite high priority right?

Also, the new Material You redesign turned out great, congratulations :)

**Comment by pioucraft** [comment]
Still waiting...

**Comment by rubcap** [comment]
Hope this feature can be added soon :hand_with_index_and_middle_fingers_crossed:, as I know have to switch to the web view just to follow a hashtag.
