### ISSUE TITLE
Wrong images displayed

### ISSUE THREAD

**Issue by floscher** [mastodon/mastodon-android#297]
When I search for person A first and the for person B, then in the search results for person B several of the search results are shown with profile pictures of (apparently random) accounts that actually were in the search results for person A.

Reloading the search results usually fixes this usually, but it can be really confusing at times.

Also, today I experienced the same issue with an image attached to a toot. The toot had a content warning, when I clicked on it, an image from another toot appeared, which I had read a few hours earlier. The image was stretched vertically to fit the aspect ratio of the actual toot image. After reloading the toot twice, a blurred version of the actual image appeared (as described in #184).

I mainly experience this, when on the go, so maybe has to do with poor internet connection.

My device is a OnePlus 6 with Android 11 (OxygenOS) running version 1.1.3 of the Mastodon app.

**Comment by scottiefalkon** [comment]
This is a common issue on the Android app. Image loading and caching seems
to just not be handled correctly at all.

**Comment by grishka** [comment]
And I thought I had image loading figured out... 😭

**Comment by stephen304** [comment]
I have a pretty fast connection so I experience this but very briefly - from my perspective it seems like just a caching issue where the previous images need to be cleared when for example the search changes. Maybe a pulsing placeholder could be put there while it loads: https://stackoverflow.com/questions/45675344/lazy-load-style-text-as-seen-on-new-youtube-design#answer-51377123 (I know this code probably isn't very useful for android but this was the first example I found - I really like the wave effect)

**Comment by scottiefalkon** [comment]
Been saying this for months. Image loading is terrible.

**Comment by grishka** [comment]
Does this only happen in search, or on other screens as well?

@scottiefalkon repeat it a couple more times maybe, that'll definitely help.

**Comment by grishka** [comment]
You're trying really hard to pass this off as something obvious, the "could you at last just open your goddamn eyes and just see it in front of you" sort of thing, but I'm just not seeing it. Images load fine. I've used this image loader in multiple different projects over the years. There were no complaints.

Yes, I do have an actual Android device.
![photo_2022-11-08_07-28-49](https://user-images.githubusercontent.com/1478258/200475250-bb4cc383-632c-40cc-832d-9a16153e79de.jpg)
This picture is from 2016, but I've only got more of them since.

Either way, your criticism is not constructive. Just saying "this is terrible" without further details can't possibly help anyone fix anything.

**Comment by scottiefalkon** [comment]
Comedian wannabe. I'm trying to help. I don't have the answer why. I'm not
the only person with the issue. I don't have the issue with any other
Mastodon app or on the websites for any instances. There is a problem. I'm
not making it up. Don't cuss at me because you can't figure it out. Real
professional type you are over there. You wouldn't talk that way to a
client or customer. Or to me if you were in arm's length. Don't forget who
you are. I'm done with this. And you. And you smart off again and I'll post
this for the Fediverse to see. Not a threat. You got rude and sassy kid.
Fix it or don't. Like I said, look at the ratings.

**Comment by stephen304** [comment]
Here's a screencap of a few searches - it goes a bit fast because my internet is good, but the issues I can see include:

* search test - "test foobar group" briefly shows a woman's face (that's someone else I have previously searched)
  * "Test test" briefly has the profile image of one of the mastodon news accounts I follow
  * "Fediphotos lineage", same issue but with a different mastodon news account
* I press the X to clear the search bar
  * AmericanFietser briefly has the wrong icon, not sure who's profile image that one is
  * Doug Gordon briefly has Ray's profile picture
  * Cambridge Bike Lanes briefly has American Fietser's profile picture
  * Ray Delahanty has Doug gordon's profile picture until it loads correctly
* I just search "doug"
  * "Dough" has the profile picture of one of the results of the previous "test" search
  * Douglas Crockford has the profile picture of the test foobar group from before

I think you can get the idea

https://user-images.githubusercontent.com/981915/200476570-594a8dfd-bb98-4df5-b1fd-3a0cbe9e764f.mp4

**Comment by grishka** [comment]
Hm, yeah, this does feel like it's related to the way I update this particular list (I have to scroll it up because RecyclerView insists on preferring to leave the topmost item where it is on the screen despite more items being inserted above it). I'll look into it.

**Comment by floscher** [comment]
> Does this only happen in search, or on other screens as well?

As described above, toots with content warnings and an attached image seems to be another place where this happens. Sometimes an image from another toot is shown (stretched to the aspect ratio of the actual image).

**Comment by sk22** [comment]
> Also, today I experienced the same issue with an image attached to a toot. The toot had a content warning, when I clicked on it, an image from another toot appeared, which I had read a few hours earlier. The image was stretched vertically to fit the aspect ratio of the actual toot image. After reloading the toot twice, a blurred version of the actual image appeared (as described in #184).

about this problem - which is probably related to #184, not sure if the other one is, too: i just had this again, and i suppose it was my internet connection, or the server responding too slow. i scrolled down a feed (not the home timeline, but a user's post) and it kept displaying the photos i'd already seen, and sometimes no photo at all (in a loop, like; photo 1, no media, no media, photo 1, …)

**Comment by sk22** [comment]
https://user-images.githubusercontent.com/6217438/201545585-dbbf7d6b-8b54-4738-a253-3725cad6715f.mp4

here's another example (see other issue for another example) where it jumps very briefly. no idea why it happened there tho. i just scrolled around a lot

**Comment by sk22** [comment]
https://user-images.githubusercontent.com/6217438/201545854-d756ed3a-b9c5-443c-9c2e-4f38fe6fda5c.mp4

also, this happens sometimes (again, i don't know when and why) (and yes, this isn't the upstream app, but i didn't really touch any code that handles image loading, so just for reference)

**Comment by grishka** [comment]
>here's another example (see other issue for another example) where it jumps very briefly. no idea why it happened there tho.

Might be because of the way I hide images for CWs. Feels very hacky and I'm never 100% confident about hacky solutions.

**Comment by sk22** [comment]
here's another example:

![IMG_20221115_012520](https://user-images.githubusercontent.com/6217438/201796085-3af8ca68-54e6-4aed-a8f5-9aca717ebde9.jpg)

i found that this can be reproduced quite reliably when searching for one URL containing a photo and then for another one.

**Comment by grishka** [comment]
Appkit 1.2.7 is not on Maven Central yet because publishing things there is quite a commitment and I usually delay it until an app release, so if you wish to build the app from sources, you first have to run `:publishToMavenLocal` task on appkit.

**Comment by iyush** [comment]
> so if you wish to build the app from sources, you first have to run `:publishToMavenLocal` task on appkit.

I am trying to build it from source. Can you be more specific on how to do this?
