### ISSUE TITLE
Links in profile, About Tab not opening 

### ISSUE THREAD

**Issue by elaur** [mastodon/mastodon-android#340]
Hi,

Want to report a issue with links from profile in about tab. This are not opening doesn't matter what option I'm choosing for browser to open it. See video https://a.cl.ly/v1uQdKxj

**Comment by jeneyloo** [comment]
I visit your profile on my Android phone, it works well. Would you like to give more information: OS version, App version, it would be nice if there was a crash log.

**Comment by grishka** [comment]
Judging by the animation, the Mastodon app does its job. It's just that the receiving side of this intent immediately finishes its activity. Since it's a Threema link, if you have it installed, try clearing its defaults in the system settings. Then you'll see an intent chooser dialog next time you open that link.

**Comment by elaur** [comment]
Apparently it look like sorted, probably was because I have treema already installed and wanted to make a return back. I added another link and apparently look like is working.

**Comment by elaur** [comment]
Apparently is working with other links but not with threema links if you have it already installed. Probably the issue is from threema side.
