### ISSUE TITLE
Approval required for sign up instances are not displayed in the app

### ISSUE THREAD

**Issue by Tealk** [mastodon/mastodon-android#364]
Hello,

why are instances with the registration setting "Approval required for sign up" not displayed in the app?
Many instances protect themselves from spam or simply from being overrun, but would still get users.

**Comment by grishka** [comment]
This is intended behavior. You can sign up on such an instance by entering its domain into the search field.

**Comment by Tealk** [comment]
> This is intended behavior.

This makes me extremely sad that this is an intentional behavior.

How many users will understand about the URL? I think we lose a lot of people who do not understand the technology!

**Comment by BennyBolivar** [comment]
My brother asked me the other day why arent listed there, because he searched for our instance. We arent listed because approval is required. Maybe this is intended behaviour but its not smart at all.

We could easily host another 5000 User but we dont want spam accounts. Thats why we require approval for sign ups.

So why are we not listed anymore?

**Comment by fuerchtegottt** [comment]
The manual approver process really is a good step to prevent spam accounts. On well operated instances with already big ammounts of active users this should be no problem (regarding reaction times). Why are you discriminating against instances with high quality standards in approval?

Please change that rule.

**Comment by joho1968** [comment]
Why not simply make it a separate option ... ?

**Comment by grishka** [comment]
In the redesigned signup flow there's a filter that allows you to see the manual-approval servers.
