### ISSUE TITLE
Building the current source code is broken due to appkit 1.2.7

### ISSUE THREAD

**Issue by antmonteiro** [mastodon/mastodon-android#375]
Mastodon Android is currently broken due to dependency version (1.2.7) not existing in remote repos ([maven](https://mvnrepository.com/artifact/me.grishka.appkit/appkit))

The dependency in question is `me.grishka.appkit:appkit` and the respective version in question is 1.2.7 which was introduced by the commit https://github.com/mastodon/mastodon-android/commit/79d99a948405221b6fba7df88278ef22931709fe

Tagging the maintainer of the respective dependency @grishka

**Comment by grishka** [comment]
Yes it is. I wrote about it in a comment somewhere.

**Comment by LucasGGamerM** [comment]
And its now the new m3 redesign depends on appkit 1.2.8, which I cannot find in the appkit repo

**Comment by grishka** [comment]
The appkit repo is here: https://github.com/grishka/appkit, I also noticed there were some uncommitted changes that the redesign branch depends on, I now pushed them too.

I don't usually publish intermediate/pre-release versions to Maven Central because the publishing process is irreversible. You can build it yourself and install it to your local maven repo by clicking this:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1478258/231895123-afe89328-ba03-41a9-91d9-e69bac8b018e.png">

The local repo will take precedence over Maven Central.

**Comment by LucasGGamerM** [comment]
There is also a missing me.grishka.litex.palette dependency, which I am not sure how to get

**Comment by grishka** [comment]
Sorry, forgot about it. That's here: https://github.com/grishka/LiteX

Since this isn't subject to change because it's a fork of AndroidX, I did just push it to Maven Central.
