### ISSUE TITLE
Can't login to existing account from Mastodon Android app

### ISSUE THREAD

**Issue by marcelocra** [mastodon/mastodon-android#392]
When I open the app, I'm greeted with two options: "Comece já" (sign up) and "Entrar" (login).

Whichever I click sends me to the same screen, with the server search. And there's no option there to actually login.

I was looking through the code and it seems like the "log_in" string (that is translated to "Entrar") is not used anywhere. Not sure that's really the case or github search is just broken.

**Comment by ZapperDJ** [comment]
The current UX is totally broken. First, both buttons should not lead to the exact same screen. Furthermore if the instance you are on is not on the list, it seems like tou can't access it, as even after inputing the instance URL (which is mastodon.social in my case and one of the biggest instances) in the search field the "Next" button continues to be disabled. Turns out that you need to tap on the  "Enter" button of the keyboard to continue. I had to search on Reddit to get to this workaround even though I am very tech savvy. If I found this difficult, this must be next to impossible for a newbie that (like I did) created their account on a PC and now want to use the app

In my opinion the sign up button should work as it does now, but the login button should lead to a screen where you get asked to input your instance's URL and then get redirected to the login screen of that particular instance

**Comment by marcelocra** [comment]
> Hello @marcelocra, you can enter the URL of your instance into the Input field on the screen which you mentioned, you'll then be redirected to your instance and can login there. Hope this helps.

Yes, that helped, thanks!

> Turns out that you need to tap on the "Enter" button of the keyboard to continue

I saw that too and was lucky enough to hit it before noticing that the button was disabled.

> I had to search on Reddit to get to this workaround even though I am very tech savvy. If I found this difficult, this must be next to impossible for a newbie that (like I did) created their account on a PC and now want to use the app

I would guess that as tech savvy people we tend to use stuff on a PC.. but most people use only their phones (mobile-first), so maybe it is not that much of a deal for them? But fixing this wouldn't hurt them.

> In my opinion the sign up button should work as it does now, but the login button should lead to a screen where you get asked to input your instance's URL and then get redirected to the login screen of that particular instance.

Completely agree. The screen could even list some of the most popular ones, for simplicity.

---

Closing this as it is not a bug. Created another one (#411) for this improvement. Cheers!

**Comment by cyberpunkrocker-zero** [comment]
> Hello @marcelocra, you can enter the URL of your instance into the Input field on the screen which you mentioned, you'll then be redirected to your instance and can login there. Hope this helps.

Well I tried that, all I get is:
```
Error
mastodon.social doesn't appear to be a Mastodon instance.
Unable to resolve host "mastodon.social": No address associated with hostname

```
same error if I add _username_@ at the front.

**Comment by marcelocra** [comment]
You need the `https://` before. You should input:

```
https://mastodon.social
```

**Comment by cyberpunkrocker-zero** [comment]
Same error message with `https://mastodon.social`
I can access `mastodon.social` via a browser on the same Android phone (as with PC) without issues, so it shouldn't be a networking problem?

**Comment by iTrooz** [comment]
@cyberpunkrocker-zero I had the same issue (even the mastodon API calls to search a server failed), reinstalling the app fixed it
