### ISSUE TITLE
limit image previews to runtime

### ISSUE THREAD

**Issue by asklow** [mastodon/mastodon-android#436]
### Pitch

I'm not sure why one has to store image previews on "disk", as everything on the internet these days are temporary that last as long as a day at max.
Instead of storing previews on `@APPDATA@/cache/images`, why not limit that data on runtime ?

### Motivation

Memory is 10x faster than any disk storage. So it'll be a huge performance bump in timeline scrolling.

Unfortunately, I'm not able to set a tmpfs mount, as it needs root, as well as little bit of tinkering with scripts.

**Comment by grishka** [comment]
You didn't read the sources, did you? There are two levels to the image cache. The one is on disk, yes, but another is in memory. Both these caches delete the oldest items when a size limit is reached.

**Comment by grishka** [comment]
> Application can run fine even without caching images on disk. Improves performance even further caz you're eliminating disk writes, for which you don't need of.

Are you sure you understand what you're talking about?

**Comment by grishka** [comment]
Okay, let me explain then. **Scrolling** doesn't "use" the disk. The image loader is fully asynchronous: the downloading, the disk cache I/O, and the decoding all happen on a dedicated background thread pool. They don't affect the UI thread in any way whatsoever. On a modern device with a multi-core CPU these threads would probably even run on different cores.

The reason why there are two levels of cache is that they serve different purposes:
- The memory cache stores **uncompressed bitmaps**, the kind that takes 4 bytes per pixel. These get really huge, really fast. But, they're what you use if you want to show an image on the screen, and this cache makes them available for that purpose immediately. For some images the in-memory cache stores downscaled versions in order to conserve memory. Due to the bitmaps being uncompressed, the in-memory cache doesn't fit as many images as one might think.
- The disk cache stores **original downloaded files**. The compressed jpegs and pngs. And the disk is huge and the compressed images are small, so you can store lots of them there. The disk cache removes the need to re-download an image from the network if it got displaced out of the memory cache — which is a frequent occurrence. It also allows the cache to survive app and device restarts. It also allows you to see previously loaded images in your home timeline when you're offline, even after the app was killed since the previous time you were online.

Even if I would store compressed images in memory as another intermediate cache level, this won't help things much. And don't forget that Android kills apps quite a lot and nothing you cache in memory survives that, obviously.

And I'll say it again: your whole premise that the existence of disk I/O in the image loader somehow affects the UI performance is wrong. Since I've now explained why it works the way it does, and why your suggestion doesn't make sense, I'm closing this issue.
