### ISSUE TITLE
(minor) Issues displaying RTL correctly

### ISSUE THREAD

**Issue by imdatsolak** [mastodon/mastodon-android#506]
When displaying RTL text, the order of toot-text, to-account, and finishing "." (period) is mixed up on the official app.

Overall, the RTL toot TEXT seems to be correct, but the order of components is wrong.

## EXPECTED
It should be: (from RIGHT to LEFT): <TARGET> <TOOT> "."

![IMG_0461](https://user-images.githubusercontent.com/10852644/212675125-4d6fe767-8f2d-4f9a-8beb-2f8f700d258a.jpeg)

## ACTUAL
It is: (from RIGHT to LEFT): "." <TOOT> <TARGET>
![IMG_6425](https://user-images.githubusercontent.com/10852644/212675299-53ab4eea-e6c2-4b09-816f-98fa66cdede3.jpeg)

**Comment by grishka** [comment]
Then this indeed is down to the differences between the way iOS and Android render bidirectional text.

I'm closing this because I have no idea how to fix it without breaking a million other cases. Adding direction override control characters is one way to do it, but it feels like a dirty hack that would haunt me for the rest of eternity.
