### ISSUE TITLE
F-Droid - set updater to opt-in and make it clear it's from Github

### ISSUE THREAD

**Issue by licaon-kter** [mastodon/mastodon-android#539]
Ongoing discussion: https://gitlab.com/fdroid/admin/-/issues/371

Disabled latest for now: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12613

**Comment by grishka** [comment]
What again? Are we still doing reproducible builds or not? I remember you saying that the updater is okay as long as builds are reproducible.

If you want a build without self-updating functionality, just use the `release` flavor. Self-updating is the only difference between `release` and `releaseGithub`.

**Comment by licaon-kter** [comment]
It's about reproducible and how users could auto-update from Github/in-app to a version F-Droid never verified as such yet they could think it was build by F-Droid.

Kinda separate issues :)

I think you can check if F-Droid is installed on first start and turn that off by default.

**Comment by linsui** [comment]
We are so sorry to make the update delayed again. Could you please upload the release flavor apk somewhere?

**Comment by linsui** [comment]
> It would be strange if it would disable self-updating just because f-droid is present on device. Maybe I should check the installer package instead?

Sadly there are third-party F-Droid clients. So I thought it's easier to upload the release flavor.

**Comment by grishka** [comment]
[mastodon-release.apk.zip](https://github.com/mastodon/mastodon-android/files/10757819/mastodon-release.apk.zip)

> So I thought it's easier to upload the release flavor.

The problem is that since you're using my builds signed with my key, I'll have from now on, for the rest of eternity, provide both flavors for each release. I don't like this idea. I'd really like to have one universal build instead that would just perform all the necessary checks and enable or disable self-updating accordingly.

**Comment by obfusk** [comment]
>  I'd really like to have one universal build instead that would just perform all the necessary checks and enable or disable self-updating accordingly.

Yes, that would be great.

But we're not aware of any way to reliably detect whether a user downloaded the APK from Github or installed it from one of the various F-Droid clients (or even downloaded it manually from our website and installed it with `adb`), are you?

Whereas simply asking the user to opt-in to automatic updates is transparent and doesn't involve any guesswork as to where the APK came from.

**Comment by obfusk** [comment]
> I remember you saying that the updater is okay as long as builds are reproducible.

That was an oversight as "download[ing] additional executable binary files" is not allowed by our inclusion policy.

**Comment by obfusk** [comment]
> I'd really like to have one universal build instead that would just perform all the necessary checks and enable or disable self-updating accordingly.

Google play does not allow self-updaters. So you would need to provide two flavours either way.

**Comment by licaon-kter** [comment]
@grishka is the same APK uploaded to Play?

**Comment by grishka** [comment]
Not quite, Google Play requires app bundles (aab) now, so that's what we upload

**Comment by jugendhacker** [comment]
@grishka from the F-Droid side we would really like to get this issue done, as it does not really help anybody, if F-Droid is stuck on an old build. As far as I cant tell there are basically two options how we could continue:

1. you could upload an APK signed by you which has the updater disabled (e.g. the Play build, but as APK)
2. F-Droid could do a hard cut and switch Mastodon to it's own signature

IMHO the second option will make things quite more complicated than the first, because with different signatures users have to manually uninstall the old version and install the new one (currently they will not even get notified by the F-Droid client that there is a new version, but with a different signature). This might lead to data loses and thereby anger from the user perspective and/or users will get stuck on an old (potentially buggy) version of your app forever.

Please let us know how you would like to continue, so we could get this issue fixed.

**Comment by grishka** [comment]
> you could upload an APK signed by you which has the updater disabled (e.g. the Play build, but as APK)

Where would I upload it? I don't want to upload it to releases here because that would create confusion.

**Comment by jugendhacker** [comment]
In theory you could upload it anywhere, as long as it has a stable URL which could somehow be derived from the versionCode and/or versionName

**Comment by linsui** [comment]
Another choice provided by @TheLastProject :

> In my opinion, just one dialog window like "Note: The update you are about to install comes straight from the Mastodon development team. If you use an app store like F-Droid, be aware this update hasn't been approved by them. If that is an issue to you, wait for the update to appear in your app store." would make it compliant with policy

You may want to detect the installer so that it's not shown to the users who update mastodon with in-app updater.

**Comment by grishka** [comment]
> You may want to detect the installer so that it's not shown to the users who update mastodon with in-app updater.

But we already discussed that here and came to the conclusion that there is no universal way to automatically detect whether the user is using F-Droid. Yes, detecting the installer is straightforward, but @linsui said it's not enough.

**Comment by linsui** [comment]
It's not enough if it updates itself automatically. But it can help display less warning. If it can detect that it's installed by itself, then the warning is only shown once to the users who download it from github.

**Comment by grishka** [comment]
No, I meant that I would disable self-updating completely if the app is installed by F-Droid. Or do you want that AND a warning in other cases? What should the warning be? Simply asking whether the user wants the app to check for updates?

**Comment by linsui** [comment]
> No, I meant that I would disable self-updating completely if the app is installed by F-Droid.

We all want that but it's not reliable.

I mean that since mastodon only shows a notification asking for update, then with a warning as said above we don't need to disable the updater. The installer detector can make it more user-friendly.

> What should the warning be? Simply asking whether the user wants the app to check for updates?

The warning should make it clear that the update is from mastodon devs instead of F-Droid. An example:

> "Note: The update you are about to install comes straight from the Mastodon development team. If you use an app store like F-Droid, be aware this update hasn't been approved by them. If that is an issue to you, wait for the update to appear in your app store."

**Comment by linsui** [comment]
Of course you can add more app id to the dector so that less users will see the warning.

**Comment by grishka** [comment]
(I'm still waiting for @Gargron's decision on this)

**Comment by grishka** [comment]
We decided that we don't want reproducible builds on F-Droid because they don't really solve anything yet create too much burden. So, yes, let's "do a hard cut and switch Mastodon to it's own signature". If I knew in advance that reproducible builds would be so much of a pain in the rear, I'd never agreed to have them in the first place.

**Comment by grishka** [comment]
No — we don't even have a reliable way to communicate with these users. We don't have any analytics that would tell us the number of users affected either. My own estimate would be no more than several thousand.

Does the F-Droid app display any sort of error when you try to install an incompatible update?

> the potential data loss?

The app doesn't store any irreplaceable data so that's not a concern. You'd just have to log in again, and even that would be as easy as clicking "allow" because we use custom tabs for oauth so session cookies are stored in the user's default browser.

**Comment by jugendhacker** [comment]
> No — we don't even have a reliable way to communicate with these users. We don't have any analytics that would tell us the number of users affected either. My own estimate would be no more than several thousand.
> 
> Does the F-Droid app display any sort of error when you try to install an incompatible update?
Yes, but only if the user manually goes into the apps detail page and selects to install the newer version. Then F-Droid will display a warning that this version is signed with a different key. But the problem is, most users will not know about this, because this update will not be suggested in the updates tab. So I would say at least a post from the official Mastodon account after the cut would be good, to get at least some users informed about this, but even then my guess is that quite a lot of users will get stuck on an old version (as I said before already).

**Comment by grishka** [comment]
That feels like more of a UX problem with the F-Droid app. It knows it installed something, but then the update is incompatible, can't it still show it in the updates tab but with a warning that the app needs to be reinstalled?

**Comment by jugendhacker** [comment]
Yes this is kind of a UX problem, but there are reasons why we don't display updates with a different signature as updates. For example if the user has multiple repos added offering the same app with different signatures this will confuse users.

**Comment by grishka** [comment]
But what if they only have one repo added, or if all the apks offered by different repos are identical? This definitely feels like a technical detail that leaks into the UX "because it was easier for developers this way". It's definitely fixable. It's not a kind of issue that should require human intervention to resolve in most cases.

**Comment by licaon-kter** [comment]
If the apk are identical, with the same signature (right?), they will get an update, yes.

Hard switches are not something that it is done willy-nilly at F-Droid's behest but after consulting with upstream (aka you) and when they agree to have a way to inform (some of) their users.

Eg. We did this for Webcall recently, they used the app itself (for the default server it announces in-app), and Wireguard, they announced it on mailing list and tweets and F-Droid toots boosted those.

What's the issue to send a toot about this switch exactly?

**Comment by grishka** [comment]
> What's the issue to send a toot about this switch exactly?

The issue is that you keep trying to find a human solution to what in essence is a purely technical problem.

Also, I'm a developer, not a PR person, so we're yet again at the point where we can't proceed because the decision about how to communicate this to users on behalf of Mastodon is not mine to make. This whole thing could've been avoided if the F-Droid app handled signature changes more gracefully. This situation happens from time to time, so why not write a bit of code to handle it?

**Comment by jugendhacker** [comment]
> This whole thing could've been avoided if the F-Droid app handled signature changes more gracefully. This situation happens from time to time, so why not write a bit of code to handle it?

Although it does happen, it should not happen, because signature changes are always a security risk. Also even if our client developers change their mind and implement some easier UX for this case, it will not happen in the near future. So the best way to handle it, is to inform users about the work needed via some out of band communication channel.

And if you feel not responsible here, then please escalate this issue to whoever is responsible / has more rights to make a decision, as we also would like to get this done from our side.

**Comment by licaon-kter** [comment]
>  This whole thing could've been avoided if the F-Droid app handled signature changes more gracefully.

That's not a thing... the Android security model forbids signature changes, plain and simply. 

So not a tech issue but a human one...

How does Google do it? By having a rootkit (aka system app) and subverting the whole "security model" they'll gladly enforce for any other "competitor" when it suits them? Dunno... maybe...

>  This situation happens from time to time, so why not write a bit of code to handle it?

It happens because we _(F-Droid and users and devs)_ want to "up"-grade to RB not the other way around, to make it "better", else blog posts and toots and tweets start to drop on F-Droid's contributors heads crying that "security" is not enforced. Fun? Not really... as no hands are lent to help... only keyboards get their buttons smashed.

**Comment by licaon-kter** [comment]
> Signal, for example

First of all Signal is not reproducible from FOSS dependencies.

> The signature does not in any way influence the runtime behavior of an apk.

I agree, this was about the security protection that Android enforces, not about 1-on-1 :)

Regarding the 3 buttons UX, feel free open such a Merge Request. Sounds rather easy to wire given that all these actions are available in Client already. ;)

**Comment by TheLastProject** [comment]
I see this has gone to become a long discussion again. Let me summarize to ensure we're all on the same line.

1. As stated [3 weeks ago](https://github.com/mastodon/mastodon-android/issues/539#issuecomment-1508922267), F-Droid has no way to notify users a new version is available on signature change. While improvements to this would be nice, it is unrealistic to assume this will happen anytime soon. Just like you mentioned Eugen is really busy, F-Droid developers are too, and there is simply no capacity to pick this up right now.
2. You decided that you no longer want reproducible builds [yesterday](https://github.com/mastodon/mastodon-android/issues/539#issuecomment-1529841099).

So, as far as I see it, there are no blockers left. We're just switching to non-reproducible on your "release" flavour (which as I understand it lacks the updater the "githubRelease" flavour has) and that's it.

**Comment by jugendhacker** [comment]
For reference, I opened the corresponding [fdroiddata MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13026) to disable reproducible builds for Mastodon

**Comment by licaon-kter** [comment]
Not the fix that I've wished for...

**Comment by obfusk** [comment]
For the record:

> I already said that the way you approach reproducible builds is _strange_. Signal, for example, [does do reproducible builds](https://github.com/signalapp/Signal-Android/blob/main/reproducible-builds/README.md), but they aren't comparing entire apks byte-for-byte _including the signature and zip internals_. They instead are comparing their contents file by file. And it does make sense — if the contents of the apks (dexes, resources, assets, native libraries) are identical, then the two apks are, for all intents and purposes, identical. The signature does not in any way influence the runtime behavior of an apk.

As was explained to you before, there is nothing strange about our reproducible builds. Reproducible builds [*by definition*](https://reproducible-builds.org/docs/definition/) require *bit-by-bit identical copies* of APKs.

Whilst comparing the APK contents is certainly useful (and could be argued to be sufficient for certain use cases depending on the relevant threat model), it is not a reproducible build as it does not meet the definition. Unfortunately, Signal [does not actually have reproducible builds](https://reproducible-builds.org/reports/2022-12/#android-news).

"[...] the consensus view within the Reproducible Builds project: pursuing a situation in language or package ecosystems where binaries are bit-for-bit identical [...] is not a luxury demanded by purist engineers, but rather the only practical way to demonstrate reproducibility."

But more importantly: there is no problem with the comparison. The problem is that we need an APK (either one matching the flavour w/o the updater or one with an updater that complies with our inclusion policy) to compare to. Which you are not willing to provide.

Comparing the contents instead of the entire APK as you suggest would not in any way change that. Reproducible builds will always require a reference APK to compare to, regardless of which signature we use for the APK we publish.

And since Android does not allow switching signatures as part of its security model, we cannot switch to using our signatures (with or without RB verification) without users having to reinstall the app.

> I should never have agreed to have reproducible builds in the first place.

Fair enough. It would have saved us all a lot of time if you had made it clear from the beginning you would not be willing to continue to provide reference APKs that comply with our inclusion policy.

**Comment by grishka** [comment]
> As was explained to you before, there is nothing strange about our reproducible builds. Reproducible builds [by definition](https://reproducible-builds.org/docs/definition/) require bit-by-bit identical copies of APKs.

I've thought about it more and I came to the conclusion that this can't possibly work.

*Reproducible* builds mean that you, as the end user, must be able to reproduce them. You download a binary from somewhere, you download the source code, you build the code, and the binary you built should match the one you downloaded. You thus have *reproduced the build*. Bit-by-bit identical copies *can* work for binary formats that don't require signatures — that's pretty much all native ones (PE, ELF, mach-o, etc). They can not, however, work for apks, because of the signature, and because the user reproducing the build would sign the apk with their own key, not mine. Thus the bytes that encode the signature will necessarily differ. Thus you can't compare two apks built by different people from the exact same source as opaque binary files because they will never match.

**Comment by obfusk** [comment]
> I've thought about it more and I came to the conclusion that this can't possibly work.

The solution people came up with years ago and have been using since "can't possibly work"? Really?

> _Reproducible_ builds mean that you, as the end user, must be able to reproduce them. You download a binary from somewhere, you download the source code, you build the code, and the binary you built should match the one you downloaded. You thus have _reproduced the build_. Bit-by-bit identical copies _can_ work for binary formats that don't require signatures — that's pretty much all native ones (PE, ELF, mach-o, etc). They can not, however, work for apks, because of the signature, and because the user reproducing the build would sign the apk with their own key, not mine. Thus the bytes that encode the signature will necessarily differ. Thus you can't compare two apks built by different people from the exact same source as opaque binary files because they will never match.

You are absolutely correct that embedded cryptographic signatures pose a challenge. But there are solutions.

Have you considered reading [the documentation](https://reproducible-builds.org/docs/embedded-signatures/) provided by the Reproducible Builds project on our website?

"Software that is distributed using embedded cryptographic signatures can pose a challenge to allow users to reproduce identical results. By definition, they will not be able to generate an identical signature. This can [...] be solved by making the signature part of the build process input [...]"

This is the solution that F-Droid uses (Debian as well); [our documentation](https://f-droid.org/docs/Reproducible_Builds/) explains how our reproducible builds work.

**Comment by obfusk** [comment]
Also: when the official Mastodon app [was added to F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11874) *reproducible builds were working just fine* (and they are still working just fine for many other apps). The only complaint about publishing on F-Droid using RB from your end was that you insisted on signing with Android Studio instead of `apksigner`, which we were able to support.

The **only reason we are no longer able to provide reproducible builds for the app on F-Droid is that you are no longer willing to provide reference APKs** that comply with [our inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/).

Regrettably, there was some miscommunication regarding our policy for in-app updaters (which the app did not yet have at the time). But you already have a compliant app flavour that you upload to Google Play as an AAB, but are not willing to upload for us as an APK. You could also easily have made the flavour with the updater compliant: all we require is "explicit user consent", that it "clearly explains to users that they’re choosing to bypass F-Droid’s checks if they activate it."

**Comment by eighthave** [comment]
I hope this doesn't come across as more criticism, I think we can find a solution that makes everyone happy here.  I'd like to propose something that seems like a pretty simple solution, at least from my point of view.  And please correct me if I got any facts wrong.

How about Mastodon's in-app updater include a message dialog that prompts the user when it is switching the update channel?  E.g. if the current Mastodon APK was installed by something other than the app itself, and the in-app updater wants to update from its own channel, then it would ask the user with a standard Always/This Time/Never dialog.  This should be pretty easy to implement, based on the installer field that Android maintains for each app.  This would cover the F-Droid case, and others that are less discussed. And I think we could even find someone to submit this implementation in a pull request, as needed.

And this would also provide an example of the gold standard of combining flexible update channels, reproducible builds, upstream-controlled signatures, and user freedom.

**Comment by TheLastProject** [comment]
That was already suggested in https://github.com/mastodon/mastodon-android/issues/539#issuecomment-1508967027. The original suggestion was: "Show the alert when the previous installer was not Mastodon". This option was rejected.

It is too late now anyway, Mastodon on F-Droid is no longer on their own signature so an in-app updater will never work.

The Mastodon team also made quite clear in posts like https://github.com/mastodon/mastodon-android/issues/539#issuecomment-1529841099 that they don't see the added value of RB and find issues like these to create additional burden they want to avoid dealing with whenever possible.

Sure, RB are the "gold standard". However, the current solution is the solution that has the lowest developmental burden on the Mastodon team for the F-Droid build so they can focus on the issues they prefer to work on which, as I understand it, is one of their leading concerns.

I think we'll all be happiest moving on from this issue and just enjoying the fact that F-Droid can distribute updates again (due to the compliant `release` flavour) and that any possible future issues, if any will ever occur, can be fixed with way less stress and work on both sides.

**Comment by eighthave** [comment]
If Mastodon's installer check was only looking for "did I install this last time?" Then this check would not be affected by the presence or absence of any other app.  It would only be affected if the user updated Mastodon using a different app, e.g. F-Droid, NeoStore, Google Play, GitHub Releases via the browser, whatever.  In that case, the installer would be `not org.joinmastodon.android`.

Maybe Mastodon could have an "Always" prompt which saved its state, so it wouldn't need to prompt the user again, even if the currently installed version came from `not org.joinmastodon.android`.  I'll defer to @TheLastProject  @linsui @licaon-kter on whether that's kosher or not.

**Comment by grishka** [comment]
> If Mastodon's installer check was only looking for "did I install this last time?" Then this check would not be affected by the presence or absence of any other app.

It would mean that when they installed the app for the first time, for example from a web browser, the app would still have to show that alert. This would ruin the user experience for no good reason.
