### ISSUE TITLE
M3: Add labels to the bottom navigation bar and maybe fill the icons

### ISSUE THREAD

**Issue by HonbraDev** [mastodon/mastodon-android#614]
Currently, apps using the bottom bar have labels under the icons by default. This app does not. While it is a valid UX decision, it would be nice to have an option to turn them back on and/or annotate them when long-pressing.

The current bottom navigation bar, which is shorter than the default component and lacks labels:

![described above](https://github.com/mastodon/mastodon-android/assets/54026315/90793553-23c0-4dc6-8c87-c5f4aabd3bb2)

The demo component from the Material Gallery, which is taller than the Mastodon one and has labels on long press:

![described above](https://github.com/mastodon/mastodon-android/assets/54026315/430fc709-4147-44ce-9b20-8aed2347a90e)

The proposed configuration, with the label visibility option set to auto:

![described above](https://github.com/mastodon/mastodon-android/assets/54026315/72218532-0114-4610-8c07-265cf216423f)

The icons also don't switch to their filled variant when selected, though again this could be a valid UX decision.

**Comment by grishka** [comment]
Our UIs are designed by a professional design team. We don't accept outside contributions to the UI of the app.

**Comment by CherryKitten** [comment]
> Our UIs are designed by a professional design team. We don't accept outside contributions to the UI of the app.

have you considered just making this closed source then? lol

**Comment by Ultra980** [comment]
> Our UIs are designed by a professional design team. We don't accept outside contributions to the UI of the app.

why is this foss then :clown_face:

**Comment by ShadowJonathan** [comment]
> Our UIs are designed by a professional design team. We don't accept outside contributions to the UI of the app.

Y'know, the correct way to deal with issues like this is to pass that feedback onwards to that same design team, not to close the issue, since that's just putting fingers in your eyes and going "lalalalala cant hear you", which isn't very appriciated in open source projects.

**Comment by Kiloku** [comment]
I recommend everyone use Megalodon, which is a fork of Mastodon for Android that actually is community focused. In fact, it already has labels for the bottom bar. Not sure if I can link it here, but it's easy to find.

**Comment by yukiqt** [comment]
> I recommend everyone use Megalodon, which is a fork of Mastodon for Android that actually is community focused. In fact, it already has labels for the bottom bar. Not sure if I can link it here, but it's easy to find.

https://github.com/sk22/megalodon

**Comment by LuNeder** [comment]
> I recommend everyone use Megalodon, which is a fork of Mastodon for Android that actually is community focused. In fact, it already has labels for the bottom bar. Not sure if I can link it here, but it's easy to find.

I don’t know why people still use the official Mastodon apps, when I joined it was pretty much consensus that they completely sucked and lacked basic features? Maybe they got better with time, but idk.

For those of you in iOS, I can recommend Feditext!

> have you considered just making this closed source then? lol

They’re like that on every single piece of software they make, including Mastodon itself. Just use the forks at this point, they’re way better.

**Comment by KiitoX** [comment]
It seems to me this decision is not compliant with written policy. This issue/feature request is plainly about accessibility, and as far as I can tell this only affects the Android version of this app.

![image](https://github.com/mastodon/mastodon-android/assets/5896952/5e958aea-24da-4f5e-b85c-748492af8f0a)

This issue should at least be brought up to the design team, instead of closing it. Alternatively do us a favor and adjust that contribution policy, to reflect reality.

**Comment by flufferyomada** [comment]
> > I recommend everyone use Megalodon, which is a fork of Mastodon for Android that actually is community focused. In fact, it already has labels for the bottom bar. Not sure if I can link it here, but it's easy to find.
> 
> I don’t even know why people still use the official Mastodon apps, when I joined it was pretty much consensus that they completely sucked and lacked basic features? Maybe they got better with time, but idk.
> 
> For those of you in iOS, I can recommend Feditext!
> 
> > have you considered just making this closed source then? lol
> 
> They’re like that on every single piece of software they make, including Mastodon itself. Just use the forks at this point, they’re way better.

Its why some people use default YouTube over NewPipe as a Bad example

**Comment by ahoneybun** [comment]
Another fediverse application doing this correctly per Material Design is Sync.

![Screenshot_20240209-123658.png](https://github.com/mastodon/mastodon-android/assets/4884946/5b367aa7-4c88-4d9c-9402-e1571d3fef02)

**Comment by alkaris2** [comment]
> Our UIs are designed by a professional design team. We don't accept outside contributions to the UI of the app.

Looks your so-called "professional design team" don't understand consistency or compatibility flow of the Material UX design guidelines. That's just bad UX design to ignore the standards that have been set, looks like you're gonna have to edit your README page to now say _"Unprofessionally designed user-unfriendly app, because fuck the standards"_ oh and remove the lines that state "Contributions that improve existing functionality, performance, or accessibility should not have any roadblocks." too since clearly you're going back on what was stated on the development commits.

**Comment by Taureon** [comment]
> Our UIs are designed by a professional design team. We don't accept outside contributions to the UI of the app.

You should edit your message to remove either sentence of it.
You're either a professional, or you accept good advice from others.
Arrogance isn't professionalism, and you're keeping your app worse because you just don't want to add labels??
It would be better if you just said "we are encouraging forks".
