### ISSUE TITLE
Can the black theme be added back?

### ISSUE THREAD

**Issue by SleepzCat** [mastodon/mastodon-android#636]
The black theme is no longer available on 2.0.0 (latest fdroid release) and the normal dark theme strains my eyes at night. Is it planned to be reimplemented?

**Comment by grishka** [comment]
> Is it planned to be reimplemented?

No.

**Comment by SleepzCat** [comment]
> No.
Why? It was a nice feature, but it was just removed for no reason...

**Comment by samhenrigold** [comment]
> Why? [...] it was just removed for no reason

Hi, app designer here. The philosophy behind the new release was to make the app feel more at home on Android, so we went all out using system tokens — that's how we're able to do neat stuff like having accent colors adapt to your wallpaper. Behind the scenes, it's doing a lot of freaky black magic to mix those colors right so containers using a `surface` color background harmonizes nicely with nested text using `on-surface`. 

If we said "screw it, the `surface` and `background` tokens now map to pure black," we'd be throwing out the work the system does to balance the other colors around it.

It's also more difficult to do visual "tricks" on pure black. We can't use shadows to imply depth. If we want to show that something is "embossed" in a black surface, we can't — there's no way to get darker than pitch black. The [dark theme guidance for Material design](https://m2.material.io/design/color/dark-theme.html#usage) covers this in a bit more nuance if you're interested.

> It saves battery life on OLED screens

Maybe possibly? There's a lot of competing information online. From my understanding, on a phone-sized device with a phone-sized battery, the savings of pure black is not enough to matter. [XDA ran the numbers](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/) on a OnePlus 7 Pro and the battery difference between showing pure black and Material dark gray is 0.063%.

> Easier on the eyes in the dark

On paper, agreed. Less light blasting from your phone screen at night is good. But going back to the Material article from above, light text on gray should be better for your eyes since there's not that extreme OLED contrast ratio between pure white and pure black. For people with cognitive differences, that negative legibility is exacerbated.

**Comment by SleepzCat** [comment]
> For people with dyslexia, that [negative legibility is exacerbated](https://uxmovement.com/content/6-surprising-bad-practices-that-hurt-dyslexic-users/).
That point doesn't really matter because dyslexic people don't need to use the true black mode if it affects the legibility of text for them. It's not like you were forcing people to use it before you removed it and it wasn't the default, even for dark mode users. And even for "visual tricks" reason you gave, they could simply be disabled in true black mode, as I'm sure they're far from necessary. But other than that I guess if it's a feature you guys are so set on removing from the app then I guess I'll just switch to a different client that has more features. Thanks for the answer.
