### ISSUE TITLE
Can't registration any service by application 

### ISSUE THREAD

**Issue by a040900** [mastodon/mastodon-android#654]
Hi, for now I had a bug need to report.
When I want to registration any service including "mastodon.social" in Traditional Chinese (zh-tw) environment. After I'm done my account information and press "next", always show the toast with this information: "Validation error: locale is not included in the list." and failed to registration.

But if I change my device and application language to English, the problem was gone. I can successfully complete the registration.

I'm not sure what happened in two different languages environment, but it is a big problem for mastodon users.

Please help to fix it.

**Comment by grishka** [comment]
I tried to reproduce it myself for a bug report to the main Mastodon repo, but accidentally registered an account 🤔
![image](https://github.com/mastodon/mastodon-android/assets/1478258/d388a580-2c38-44d8-957c-65c4fea13a63)

![image](https://github.com/mastodon/mastodon-android/assets/1478258/cb96b2bd-55e6-4005-a31f-12e961d82c9f)

I was able to reproduce it by using a locale that doesn't exist at all though, so the bug is still there.

**Comment by grishka** [comment]
Actually no, it's not case sensitivity, Java locales do have the country in capitals
![image](https://github.com/mastodon/mastodon-android/assets/1478258/98fe3ef2-d0a8-41ca-8581-1eeb1843aca1)
