### ISSUE TITLE
Fratured hashtags show posts by everyone, not just the current profile

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon-android#786]
Steps to reproduce:

1. Go to a profile and the "featured" tab then load a featured hashtag

Expected behavior: You see posts by that profile only

Actual behavior: You see posts by everyone

**Comment by grishka** [comment]
(I was never told that it's supposed to work like that, but now it does)

**Comment by tenebrios** [comment]
> (I was never told that it's supposed to work like that, but now it does)

I just wanted to give an update on the wonkiness I'm experiencing with a few different things.
I'll start by saying that I'm an android user and I'm on mastodon.social. 

1. Regarding the featured hashtags list and the app store version of the app, there's no where to make that featured tag list.
I had to make the list using either the web platform or the web app. 

2. Using the app store app is pretty frustrating. At least for me it is. I have not been able to use the app for the last 2 weeks. I uninstall the app and reinstalled it, tried to log in and it couldn't retrieve the server.
This lead me to use the web app.

3. Today for some reason the stars must have been aligned just right because the app retrieved the mastodon.social server and I "briefly" was able to use the app.

4. I saw that the featured hashtag list I made using the web app DID transfer over to the app store app and the tags in the list were showing me only the posts on my profile. That was great to see.

5. After being on the app for less than 5 minutes, it became wonky. I tried refreshing and the dial just kept spinning.
If I force closed the app and opened it again, the dial was still spinning.
I Uninstalled the app and reinstalled but now it's back to nit retrieving the server.

So that is my experience 
Hopefully someone sees this and can fix it.
I'd like to be using the app over the web app because the hashtag list is viewable on the app.
I can make the hashtag list on the web app but then it's no where to be found on my profile.
So I need the app to be functioning properly. 

Lastly, can you make the featured hashtags list unlimited instead of just 10 as the limit?
