### ISSUE TITLE
Add local and federated timeline

### ISSUE THREAD

**Issue by Discostu36** [mastodon/mastodon-android#8]
At the moment there seems to be no way to access local and federated timeline. Please consider adding that feature.

**Comment by dermitdemdino** [comment]
Without this feature, the app can only be used to a very limited extent.

**Comment by Akselmo** [comment]
Dont really see a point using this app without the local timeline.

**Comment by vilbi** [comment]
Good design, but in the last small New users waves in Germany I was in contact to several New Accounts wit the android Mastodon APP. They totally misunderstood the mastodon Federated and decantral aspect, as they don"t geht the Chance to feel it via this app. 
So add Laval and federated timeline, otherwise the approach of small decentral and diverse alternative network will die and mastodon.social will be as social as Twitter.

**Comment by dusnm** [comment]
On one hand I do understand the motivation in removing these timelines and I can begrudgingly accept that it probably is the best option for users coming from twitter. On the other hand I can't help, but feel this betrays the already existing user base, especially the users from smaller instances. The whole point of the Local timeline is to have a space for discussion with like minded people. That's why we have communities built around different themes. In essence that's exactly what separates Mastodon from Twitter. I don't want just an open source version of Twitter, that's not what I signed up for.

I feel there could be a sort of compromise here. Instead of outright removing the Local and Federated timelines, just hide them by default. That way people who know about them can use them, others don't even have to be aware of their existence.

**Comment by FediVideos** [comment]
It seems like the problem is this:

On large instances, the risks of a Local timeline outweigh the benefits. On large instances, the Local timeline is a firehose just like Federated, impossible to read and full of potentially nasty content but impossible to browse for fun. Seems like a no-brainer to zap Local.

On small instances, it's the other way around. The benefits of a Local timeline outweigh the risks, it's not a firehose, it helps build the community and people are much less likely to see nasty content because the moderators have better control over troublemakers. Removing Local seems like a bad idea.

I'm not sure how this situation can be resolved, maybe Local could be for instances below a certain size?

**Comment by afk-mario** [comment]
You can access the local timeline under search/community

**Comment by oufmilo** [comment]
I think **global timeline** is very important for smaller  instance. You need this to discover other people and to expand your visibility.

**Comment by grishka** [comment]
Local timeline was added (search -> community), and I believe there are no plans to add the federated timeline (@Gargron correct me if I'm wrong). One issue with adding a federated timeline is that it's more-or-less unmoderated and thus adds a non-zero risk of app stores, especially Google Play, rejecting the app over something outside of our control.

**Comment by Gargron** [comment]
> I think **global timeline** is very important for smaller instance. You need this to discover other people and to expand your visibility.

The explore tab is in essence a moderated, quality-filtered federated timeline. Its purpose is to help you discover other people and expand your visibility, but without being a vector for spam and abuse.

**Comment by yoshimo** [comment]
>One issue with adding a federated timeline is that it's more-or-less unmoderated and thus adds a non-zero risk of app stores, especially Google Play, rejecting the app over something outside of our control.

Do you have a specific play store rule in mind for that?

**Comment by Gargron** [comment]
> > One issue with adding a federated timeline is that it's more-or-less unmoderated and thus adds a non-zero risk of app stores, especially Google Play, rejecting the app over something outside of our control.
> 
> Do you have a specific play store rule in mind for that?

Examples from Mastodon apps specifically:

- [Tusky has been removed from the Play Store](https://chaos.social/@ConnyDuck/105904002285019275)
- [Fedilab has been removed from the Play Store](https://qoto.org/@freemo/104765288863293481)
- [Subway Tooter threatened to be removed from the Play Store](https://subwaytooter.hatenadiary.jp/entry/2020/09/01/161533)

Examples from other decentralized apps:

- [Element has been removed from the Play Store](https://element.io/blog/element-on-google-play-store/)

Examples from non-decentralized apps with user generated content:

- [Tumblr removed from the Apple App Store](https://www.theverge.com/2018/11/20/18104366/tumblr-ios-app-child-pornography-removed-from-app-store)

While all of them have been reinstated since with varying degrees of changes (Tumblr ended up banning all adult content from its platform altogether to avoid the issue), it is evident that Google (and Apple) hold apps accountable for user-generated content.

**Comment by sk22** [comment]
This commit of mine https://github.com/mastodon/mastodon-android/commit/318d271127be441ada22cff9d96ec74fcaa3d873 implements the federated timeline - you can use my fork, which has this and more features the official app won't implement: https://github.com/sk22/mastodon-android-fork#changes

**Comment by Doomsdayrs** [comment]
There is now a conception going around, from users using the official Mastodon application, that once you join an instance, you're in an echo chamber.

If smaller developers of Tusky can get their application back on the play store, Then larger organizations such as Mastodon should have no problem negotiating with larger corporations.

Example of Misconceptions being spread.
https://mobile.twitter.com/VeryBadLlama/status/1589086085380190209

**Comment by thekalinga** [comment]
I'm not sure why this issue is closed. All the links posted by @Gargron are resolved.

What Play Store & Apple Store did makes no sense & so does the reasons provided.

If paedophiles watch child porn on chrome browser/safari in their mobiles (which they do), are Google/Apple going to remove these browsers from the store? Browser is just a client. It has no obligation to spy on users as to what content they are watching (if it spies, no one will use it even for legitimate purpose, let alone pedos).

This client app is just a tool to connect to any mastodon server & load content. Since the app got no control over the servers (nor should it), there is no good reason to ban official Mastodon app, let alone other clients. Here are my reasons why they cant ban this app for meeting basic expectations

1. What Apple & Google did makes no sense (explanation above)
2. Since mastodon has good visibility now, there will be tremendous public pressure to back off
3. Many lawyers would be willing to fight against unjust ban (if Big Tech bullies bans)

These Big tech bullies must have assumed people wont complain if they bully app developers (which they know they can do, thanks to "legal" monopolies they have which they ensured thru bribes to politicians to not break these monopolies), but since mastodon is mainstream app, they cant bully that easily now.

Incase of twitter, the data is stored on twitter servers. So, Apple & Google can bully. But incase of mastodon, the app has no business to know which instance its talking to & what content is being stored in it. So, this app cant be held liable to for any harmful content.

If issue is the threat of banning (which imo is not a legitimate concern), why not publish multiple versions of app to playstore, where new development happens on a canary version (to test waters in playstore will all experimental features), while main app is still available for download incase if canary version is banned (unlikely)?

(or)

Publish an canary version to non-google repos (but still certified by repo maintainers to be malware free) so people can try out that version before these changes are graduated into main repo?

**Comment by nemobis** [comment]
> a vector for spam and abuse

I understand this concern on giant instances like mastodon.social, where there will always be something improper in the federated timeline, but the experience on other instances is very different. Some options could be:
* make the federated timeline available only for smaller instances (under 500 active users?),
* make the federated timeline available only for instances with closed registration/registration by application,
* only show posts older than 8 hours (or whatever) on the federated timeline, so that there's time to moderate them;
* give some control to instance admins to decide whether the federated timeline will be shown to their users.

Of course at the moment mastodon.social looms large https://github.com/mastodon/mastodon-ios/issues/1023#issuecomment-1617386974 but in the future if the app gives more choice to users again we'll be able to see whether access to the federated timeline makes a difference in terms of user retention etc.
