### ISSUE TITLE
Gif auto play on app

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#816]
The web app has a gif auto play setting.
The app store app needs this as well

![Screenshot_20240324_224117_Chrome](https://github.com/mastodon/mastodon-android/assets/161815189/3ea526f4-900c-406e-a7dd-983500e99fb7)

**Comment by tenebrios** [comment]
> Duplicate of [#830](https://github.com/mastodon/mastodon-android/issues/830)

Is there going to be a gif auto play setting for the app like there is on the web app?

**Comment by grishka** [comment]
Maybe. Maybe not. We don't know.

It's not very easy from the technical side of things because these "gifs" are actually silent h264 videos. In particular, some devices have a limitation on the number of simultaneously playing video streams due to the limited capacity of the hardware-accelerated video decoder. And I don't feel like bundling ffmpeg into the app just for this, to do the decoding in software instead.

**Comment by tenebrios** [comment]
> Maybe. Maybe not. We don't know.
> 
> It's not very easy from the technical side of things because these "gifs" are actually silent h264 videos. In particular, some devices have a limitation on the number of simultaneously playing video streams due to the limited capacity of the hardware-accelerated video decoder. And I don't feel like bundling ffmpeg into the app just for this, to do the decoding in software instead.

That's fine
I suppose it's not a big deal
