### ISSUE TITLE
Please Add Changelog to F-Droid Store Listing.

### ISSUE THREAD

**Issue by Coehill** [mastodon/mastodon-android#858]
Other apps list a changelog but Mastodon does not.

Additionally, other apps offer a "NEW IN VERSION ..." Header on the app store listing so you fan see what's been updated at a glance. 

![Screenshot from F-Droid Store](https://github.com/mastodon/mastodon-android/assets/13023025/d7cd8062-1751-4456-b046-733da7ab2423)

**Comment by grishka** [comment]
I do provide changelogs in the Fastlane format that F-Droid is supposed to pick up: https://github.com/mastodon/mastodon-android/tree/master/fastlane/metadata/android/en-US/changelogs

Though I just looked at [Fastlane docs](https://docs.fastlane.tools/actions/supply/#changelogs-whats-new) and it turns out my assumption that it uses the newest file if a changelog isn't provided is wrong. That's very inconvenient for how I sometimes do several consecutive releases in a short timespan with just bug fixes.

**Comment by linsui** [comment]
You can add default.txt as a link to the latest changelog and it will be used as a fallback.

**Comment by grishka** [comment]
I've done that, so I suppose this can be closed. Hopefully I won't forget to keep that symlink up to date 🙃
