### ISSUE TITLE
Feature: (Behavior) Automatically display content with content warnings

### ISSUE THREAD

**Issue by crawlserv** [mastodon/mastodon-android#87]
Hi!
The only thing I miss from the official app compared to other apps such as Tusky is that I cannot change the behavior of automatically hiding content with content warnings. (Could be added as another option under "Behavior" in the Settings.)
Thanks!

**Comment by danielcherubini** [comment]
This seems like a bug where the app ignores your content settings on your account.

FYI you can change those settings on your account on the web 

Preferences > Appearance
![image](https://user-images.githubusercontent.com/399473/166158729-cafb3d94-1889-4d2d-815a-c38ed31eee0d.png)

**Comment by grishka** [comment]
> This seems like a bug where the app ignores your content settings on your account.

The code to read, let alone respect, this setting was never written in the first place 🤔

**Comment by sk22** [comment]
If such option is implemented, the content warning should still be displayed somewhere (maybe above the toot), as content warnings often contain valuable extra information or are used like headings.

**Comment by danielcherubini** [comment]
Using content warnings as headings seems like a really bad use of content warnings. 

The idea is to say what content is in them so people who are sensitive to that kind of content can judge if they want to see it..

It's not meant to be used like some kind of extra thing that's part of the post behind it. 

If people are using content warnings like that, then they are using them wrong. 

I don't need content warnings. I'm not sensitive. But others are and I think it's a good feature to have.

**Comment by sk22** [comment]
> Using content warnings as headings seems like a really bad use of content warnings.
> 
> The idea is to say what content is in them so people who are sensitive to that kind of content can judge if they want to see it..
> 
> It's not meant to be used like some kind of extra thing that's part of the post behind it.
> 
> If people are using content warnings like that, then they are using them wrong.
> 
> I don't need content warnings. I'm not sensitive. But others are and I think it's a good feature to have.

well, lots of people are already using the content warnings "wrong", and it doesn't matter, since every major mastodon app displays them in some way. i like having my content warnings extended by default as well, but completely hiding then would be counter-intuitive as people tend to put important information in there; some toots don't even make sense without the cw. and also, in code, the content warning is called "spoiler text", so there's some room for interpretation about how to use this field. you won't be able to make everyone use it "correctly" either way, so hiding the content warning would be a bad idea imo

**Comment by ashwebcode** [comment]
Is it possible to also apply this to notifications? It would be great to see the full text in the notification if the content warnings are set to expand
