### ISSUE TITLE
Not able to load Pixelfed feed (pixelfed.social)

### ISSUE THREAD

**Issue by ahoneybun** [mastodon/mastodon-android#88]
### Android version:
12.1 (Pixel 6)

### Mastodon version:
1.0.2 (Released 4/21/22)

### What's happening:
Error message appears after signing into Pixelfed account:

`Required field 'createdAt' of type instant was null in Status`

### What's expected:
Pixelfed feed would appear.

**Comment by TheOPtimal** [comment]
Use a Pixelfed app.

**Comment by ahoneybun** [comment]
The application allows you to add a Pixelfed server which means it is meant to support it.

**Comment by grishka** [comment]
No? The fact that it allows you to add a Pixelfed server only means that the API is compatible enough for the server to be added, but not compatible enough for it to work. It doesn't signify anyone's intentions.

p.s. I hate string-based timestamp formats with a burning passion

**Comment by ahoneybun** [comment]
I'm not expecting magic but some folks may be confused as they can put the URL and sign in but it does not work. If it doesn't work that's fine but it needs to be more clear.

**Comment by cassidyjames** [comment]
Is this a case where the error could be made more user-friendly, though? There is understandably a lot of confusion around what "federation" means, and people see that they can follow and interact with Pixelfed accounts, so it's not a major leap to think they'd be able to sign into those accounts, too. I'd suggest something straightforward like:

>**Oops! That doesn't look like a Mastodon server.**
>The Mastodon app only works with Mastodon servers. Double-check that the URL you entered is for a Mastodon server.

**Comment by FediVideos** [comment]
> The app is named Mastodon, it should be quite clear it's intended to be used with Mastodon...

Is this a deliberate thing where Mastodon has blocked non-Mastodon servers from working, or is it that non-Mastodon servers aren't being compatible enough with the Mastodon API?

I had understood PixelFed had made alterations to their software so that they would be compatible with the Mastodon API? If this is an open standard, wouldn't that mean such servers could be signed into with the official Mastodon app?

**Comment by Gargron** [comment]
> Is this a deliberate thing where Mastodon has blocked non-Mastodon servers from working

We do not deliberately block anything. We don't know what software a server runs if it responds to the API requests.

> If this is an open standard, wouldn't that mean such servers could be signed into with the official Mastodon app?

The Mastodon client-to-server API is not an open standard, and not a standard at all! It's just our API for Mastodon.

**Comment by connyduck** [comment]
> The Mastodon client-to-server API is not an open standard, and not a standard at all! It's just our API for Mastodon.

Since it is implemented by multiple platforms now, it should actually be a standard though.

**Comment by noellabo** [comment]
Mastodon's API is defined for use by Mastodon itself.

Server software other than Mastodon may adopt such a strategy, since implementing Mastodon's API has the advantage of making client applications for Mastodon available.

However, efforts to maintain API compatibility should be made by the server software that wishes to be compatible; there is nothing that should be required of Mastodon or Mastodon client applications.

Issues or pull requests should be directed to the Pixelfed github.

**Comment by noellabo** [comment]
Resolved by improving Pixelfed's API response.
https://github.com/pixelfed/pixelfed/pull/3499

BTW, the Mastodon API date format is interpreted by the client app more strictly than the documentation states.

"2022-05-20T20:33:15+00:00" will not be accepted.
"2022-05-20T20:33:15.000Z" will be accepted.

**Comment by grishka** [comment]
(btw, string-based date formats suck)
