### ISSUE TITLE
Mastodon mobile app doesn't display custom emojis that have a dash in them

### ISSUE THREAD

**Issue by micr0-dev** [mastodon/mastodon-android#889]
Mastodon mobile app doesn't display custom emojis that have a dash in them. Such as :hiroi-laugh: 

**To reproduce**
1. Go to a post that has custom emojis with a dash (such as: https://fuzzies.wtf/@micr0/113115307962753519)
2. See that the emojis are not rendered on the Mastodon mobile app at all.

Expected behavior:
![image](https://github.com/user-attachments/assets/eff95d9f-96d3-47fb-a528-aab26fe0968d)

Observed behavior:
![image](https://github.com/user-attachments/assets/1b8c7765-10d6-483b-8d56-031188482000)

This behavior was initially spotted in Moshidon, but is present in the upstream Mastodon app as well therefore I'm opening the issue here.

**Comment by residualentropy** [comment]
Just for reference purposes, here's a fix in the Chuckya fork (credit to @cyrus@wetdry.world for bringing this up): https://github.com/TheEssem/mastodon/pull/9

**Comment by grishka** [comment]
Actually, they don't show up in the web app either 🤔
![image](https://github.com/user-attachments/assets/d90af37f-6834-4d67-838d-8cdbcb972d67)

**Comment by micr0-dev** [comment]
but they exist, not only on forks of mastodon (which is the case here) but also on misskey and its derivatives 

of you vists fuzzies.wtf you will see that they are there and display properly

**Comment by grishka** [comment]
This app only supports features present in the upstream Mastodon. Misskey has an incompatible API so I'm not sure which apps support it, this one definitely doesn't (I tried pointing the app to misskey.io of curiosity several days ago while refactoring, it doesn't even implement `/api/v1/instance`).

So anyway, since the server itself doesn't recognize emojis with dashes (see above), you should create an issue in the [main Mastodon repo](https://github.com/mastodon/mastodon). It would've been an app bug if the server returned these emojis but the app wouldn't render them.

**Comment by micr0-dev** [comment]
Alright thanks, there already is a issue open in the main repo, this can be closed until the mastodon repo implements support

https://github.com/mastodon/mastodon/issues/31854
