### ISSUE TITLE
Missing lists

### ISSUE THREAD

**Issue by retiolus** [mastodon/mastodon-android#89]
Cannot create lists and also unable to create lists. Please add this feature to Mastodon android.
Thanks.

**Comment by Gargron** [comment]
This is planned.

**Comment by brimwats** [comment]
still a major missing feature, fwiw I haven't found a client that does provide this.

**Comment by pauljacobson** [comment]
I'd also love to see this in the Android app. I add people I follow to lists and because I use a mobile app more frequently, I'd really like to at least be able to have the same list management and list view options in the Mastodon app for Android that we have in the web app.

Is there a roadmap for the mobile apps, @Gargron ?
