### ISSUE TITLE
Notifications don't display poll results

### ISSUE THREAD

**Issue by buerviper** [mastodon/mastodon-android#898]
After the most recent update, finished polls in the notifications don't show the poll results anymore, but just the link to the poll post (see screenshot).
![Screenshot_20241004-094659~3](https://github.com/user-attachments/assets/c4d87674-d687-4069-9741-26ed8e6cd2e7)

App Version: 2.7.0 (119)

**Comment by grishka** [comment]
This is an intentional design change ¯\\\_(ツ)_/¯
cc @samhenrigold

**Comment by buerviper** [comment]
> This is an intentional design change ¯\_(ツ)_/¯ cc @samhenrigold

Ok, but is there a specific reason why it deviates from the browser UI so much? Is the poll results screen to large for the notifications tab? Then I think something like a collapsed post and a "Show results" button within the notifications tab would work a bit better and closer to the browser experience.

**Comment by samhenrigold** [comment]
It’s because I want the notification list to remain as terse as possible. The issue is that, previously, posts take up an enormous amount of space in this list. It’s better with grouped notifications, but it’s still quite rough especially on smaller devices or people with larger font size preferences.

So to help with information density, posts in the notification list gets rendered as an inline presentation at the cost of attachments. This shouldn’t be too much of a loss since most of the posts you’ll see in here are your own and you’re probably quite familiar with them. Polls are tricky though, but then we have to design a special case for polls within an inline post and then we have to explain the rationale for not showing polls for your OWN inline posts and it becomes a mess. So it’s just conceptually cleaner this way. Replies still render as full posts in the notification list, though.

As for the browser experience, it’s getting the same visual styling in the public release of Mastodon 4.3 next week.

**Comment by buerviper** [comment]
Mh, I follow and see the mess. Not sure I like it, maybe it's just a matter of getting used to it. 
Anyway, not a bug then.
