### ISSUE TITLE
Rendering issue with code block

### ISSUE THREAD

**Issue by mpldr** [mastodon/mastodon-android#912]
https://spookygirl.boo/notes/9zkcmqpzzwpker4h

The rendering of this post is broken on the latest version from Play

![Image](https://github.com/user-attachments/assets/9eca63d1-dade-402d-a791-cf8c6996edb0)

**Comment by grishka** [comment]
It's a bug in Misskey or whatever of the thousand forks this is. This post is also broken, albeit less so (see #907), in the Mastodon web app:
![Image](https://github.com/user-attachments/assets/c9646b62-ea4d-4e51-84f4-0216af7e7f2c)
This is because the originating server didn't escape the `<S>` and `<B>` in the code block:
![Image](https://github.com/user-attachments/assets/4b1fea2e-4552-45f1-8d94-1554fe571227)

**Comment by grishka** [comment]
I'm closing this because while still "incorrect" compared to the origin server, the rendering in the app now matches the web:
![Image](https://github.com/user-attachments/assets/5018aaba-f27a-4577-a127-ab2a8b7faf0e)

You should create an issue in Misskey about `<` and `>` in code blocks not getting escaped when rendering Markdown to HTML for federation.
