### ISSUE TITLE
Characters size in one of the profile's tag.

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#930]
Characters size in one of the tabs in my profile seems to be bigger than the others (see attached picture for precise information), so the Spanish translation splits the word into two parts.
I mean the first tab next to the Timeline one.
![Image](https://github.com/user-attachments/assets/3f37716d-b836-4e14-a517-af288031a39f)

**Comment by grishka** [comment]
Oops. The tabs shouldn't even wrap to a second line, they should scroll instead. But at least it doesn't crash 😤

**Comment by grishka** [comment]
I made the text in these tabs truncate if it doesn't fit, but ideally, translations shouldn't be this long. I don't know Spanish nearly good enough to suggest better ones though.

![Image](https://github.com/user-attachments/assets/33fc115d-8445-49f2-a786-2c16b2aa5481)

(I used to run into similar problems all the time in all kinds of apps with Russian translations too, so much so that I decided to set my phone to English)

Maybe @samhenrigold can suggest a better solution (in Figma these tabs are equal width).

**Comment by jotaluissoy** [comment]
Spanish translation is perfect there. 
"Linea de tiempo" seems to be a phrase, but it is the only way to translate Timeline.
Truncating is a good idea.
Another good idea could be moving "tiempo" to a second line, something like:

Línea de
tiempo.

😉

**Comment by samhenrigold** [comment]
I guess they could scroll eventually but it seems like a lot of work for this ticket that’s already closed
